buggy conection with express
gromaxe/2018-FS-11-Frontend-Gromov pull request #4
Opened 2018-12-21 16:01 UTC by gromaxe

-поднят простой сервер на express
-основное состояние на сервере; на фронте - копия
-сообщения отправляются на сервер
-отправленные сообщения отобрааютя в чате

Проблемы:
-не смог перевести express на ES6, поэтому пришлось разделить store
-сообщения отображаются не сразу, иногда надо выти из чата и зайти
-не до конца понял, как отлавливать окончание загрузки данных из fetch
-есть лишние файлы

 node src/express-server.js - запуск сервера

2018-12-22 07:23 UTC, martinkomitsky commented
>окончание загрузки данных из fetch

Используй `.then(callback)`: https://learn.javascript.ru/fetch

>сообщения отображаются не сразу, иногда надо выти из чата и зайти

Этот пункт исправится, если починить `fetch` с `then`?

2018-12-23 14:39 UTC, martinkomitsky commented on src/App.js
> +                    if(typeof (this.props.chats)!=='undefined') {
Вообще, можно написать `if (this.props.chats)` - будет `true`, если придет непустая строка. Но, как я вижу, тут у тебя эта проверка стоит внутри `case 'chat'`, что сразу говорит о том, что это не есть пустая строка)

2018-12-23 14:41 UTC, martinkomitsky commented on src/App.js
>                  case "chatList":
тут что-то адовое происходит. Если ты решил так сделать маршрутизацию, то не советую использовать такой подход, у тебя с этим спокойно из коробки справляется `React Router`

2018-12-23 14:43 UTC, martinkomitsky requested changes
чутка допилить

2018-12-23 14:43 UTC, martinkomitsky commented on package.json
>      "html-webpack-plugin": "^3.2.0",
Не нужен этот модуль

2018-12-23 14:43 UTC, martinkomitsky commented on package.json
>      "extract-text-webpack-plugin": "^4.0.0-beta.0",
Не нужен этот модуль

2018-12-23 14:44 UTC, martinkomitsky commented on package.json
>      "css-loader": "^1.0.0",
Не нужен этот модуль

2018-12-23 14:44 UTC, gromaxe commented on src/App.js
>                  case "chatList":
Мне показалось, то так будет проще:
с index.js в зависимости от пути рендерится <App/> со страницей, указанной в props, app подгружает состояние приложение с сервера и после этого идёт на нужную страницу

2018-12-23 14:44 UTC, martinkomitsky commented on package.json
>      "css-loader": "^1.0.0",
и ниже style-loader тоже

2018-12-23 14:58 UTC, gromaxe commented on src/App.js
> +                    if(typeof (this.props.chats)!=='undefined') {
Это проверка на то, что список чатов загружен.
Осталась с тех времен, когда я не сделал весь рендеринг через App

2018-12-23 15:02 UTC, martinkomitsky commented on src/App.js
> +                    if(typeof (this.props.chats)!=='undefined') {
но ты же понимаешь, что сейчас эта проверка бессмысленна?

2018-12-23 15:03 UTC, gromaxe commented on src/App.js
> +                    if(typeof (this.props.chats)!=='undefined') {
Исправил

2018-12-23 15:08 UTC, martinkomitsky commented on src/App.js
>                  case "chatList":
Выглядит, как костыль. У тебя должен быть компонент `Router.js`, куда ты из `App.js` передаешь `props.authorized`, ну и дальше все рисуется само

2018-12-23 15:09 UTC, gromaxe commented on src/App.js
> +                    if(typeof (this.props.chats)!=='undefined') {
Удалил проверку

2018-12-23 15:16 UTC, martinkomitsky approved these changes

2018-12-23 15:16 UTC, merged

2018-12-23 15:16 UTC, martinkomitsky commented
5